In [1]:
import qstock as qs

# 宏观经济指标
## GDP

In [2]:
gdp = qs.macro_data('gdp')
gdp.head(5)

,季度,国内生产总值,第一产业,第二产业,第三产业,国内生产总值同比,第一产业同比,第二产业同比,第三产业同比
0,2024年第1-3季度,949745.7,57733.1,361361.6,530651.1,4.8,3.4,5.4,4.7
1,2024年第1-2季度,616836.0,30660.0,236529.9,349646.1,5.0,3.5,5.8,4.6
2,2024年第1季度,296299.5,11538.4,109846.3,174914.7,5.3,3.3,6.0,5.0
3,2023年第1-4季度,1260582.1,89755.2,482588.5,688238.4,5.2,4.1,4.7,5.8
4,2023年第1-3季度,912692.0,56330.1,348885.6,507476.2,5.2,4.0,4.4,6.0

In [23]:
cpi = qs.macro_data('cpi')
cpi.tail(3)

,月份,全国同比,全国当月,全国环比,全国累计,城市同比,城市当月,城市环比,城市累计,农村同比,农村当月,农村环比,农村累计
200,2024年09月份,0.4,100.4,0.0,100.3,0.4,100.4,-0.1,100.2,0.6,100.6,0.1,100.3
201,2024年10月份,0.3,100.3,-0.3,100.3,0.2,100.2,-0.3,100.2,0.3,100.3,-0.3,100.3
202,2024年11月份,0.2,100.2,-0.6,100.3,0.1,100.1,-0.6,100.2,0.2,100.2,-0.6,100.3